import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#0d0096",
        "on-background": "#dae2fd",
        "on-error": "#690005",
        "on-tertiary": "#3c0091",
        "tertiary-container": "#a078ff",
        "error-container": "#93000a",
        "surface-container-high": "#222a3d",
        "primary": "#c0c1ff",
        "surface-container-lowest": "#060e20",
        "secondary-container": "#39485a",
        "surface-container-highest": "#2d3449",
        "on-secondary": "#233143",
        "inverse-surface": "#dae2fd",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#a7b6cc",
        "tertiary": "#d0bcff",
        "primary-fixed": "#e1e0ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "tertiary-fixed": "#e9ddff",
        "secondary-fixed": "#d4e4fa",
        "on-surface": "#dae2fd",
        "surface-tint": "#c0c1ff",
        "background": "#0b1326",
        "surface-container": "#171f33",
        "on-primary-fixed": "#07006c",
        "primary-container": "#8083ff",
        "on-secondary-fixed-variant": "#39485a",
        "outline": "#908fa0",
        "surface-dim": "#0b1326",
        "on-tertiary-container": "#340080",
        "on-tertiary-fixed-variant": "#5516be",
        "inverse-primary": "#494bd6",
        "surface-bright": "#31394d",
        "secondary-fixed-dim": "#b9c8de",
        "outline-variant": "#464554",
        "error": "#ffb4ab",
        "surface": "#0b1326",
        "secondary": "#b9c8de",
        "on-primary": "#1000a9",
        "surface-container-low": "#131b2e",
        "inverse-on-surface": "#283044",
        "on-secondary-fixed": "#0d1c2d",
        "on-tertiary-fixed": "#23005c",
        "primary-fixed-dim": "#c0c1ff",
        "surface-variant": "#2d3449",
        "on-surface-variant": "#c7c4d7",
        "tertiary-fixed-dim": "#d0bcff"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
